### ISSUE TITLE
Min limit is missing from Limit Ranges

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1029]
**Description**

**Expected result**

We should see the Min Limit Range

**Actual result**

**Steps to reproduce**

Add the next limit range and notice the UI

```
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
    - type: Container
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 50m
        memory: 50Mi
      default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 50m
        memory: 50Mi
```        

**Troubleshooting**

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/478866/156125370-f6f6fa14-bcde-4a10-88e3-03aaeed9e307.png">
Min
