### ISSUE TITLE
Cannot read properties of undefined (reading 'map') on virtualservice detail screen

### ISSUE THREAD

**Issue by nexus49** [kyma-project/busola#1054]
**Description**

When accessing a detail page of a  virtual service on a non kyma cluster the page does not load and is the following error in the console logs:

![image](https://user-images.githubusercontent.com/52737/156566866-226e3b3e-4384-4346-89bc-54c19ab851c8.png)

Browser URL: https://dashboard.dev.kyma.cloud.sap/cluster/my-cluster/namespaces/some-namespace/virtualservices/details/some-name

The obfuscated version of the virtualservice that leads to this error looks like this:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  generation: 2
  labels:
    app.kubernetes.io/instance: dxp-some-value-lrr44-dxp-dev
  name: some-name
  namespace: some-namespace
spec:
  gateways:
  - gatewayname.some-namespace
  hosts:
  - subdomain1.subdomain2.domain.com
  - subdomain3.subdomain2.domain.com
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      allowOrigin:
      - '*'
    route:
    - destination:
        host: service-name.some-namespace.svc.cluster.local
        port:
          number: 8080
```
