### ISSUE TITLE
Wrong Service creation suggestion

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1312]
**Description**

When creating a Service using Monaco editor, we receive a warning, that the Service's targetPort has the wrong type (int) and suggests using a different one (string). That's not right, Service's targetPort might be an int, or might be a string but only if you add a letter to it. 

<img width="645" alt="Screen Shot 2022-05-10 at 10 06 57" src="https://user-images.githubusercontent.com/40663133/167580957-4f52e047-4e20-400f-920f-b54899bddfa0.png">

If a user wants to have for example targetPort `9376` and try to change it to `"9376"`, as warning suggests, the creation will fail.

<img width="430" alt="Screen Shot 2022-05-10 at 10 13 29" src="https://user-images.githubusercontent.com/40663133/167581595-3691ffb3-4895-40a8-b9d5-12e6c131b250.png">

According to the schema:

```
targetPort:
  description: "IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number."
  format: "int-or-string"
  type: "string"
```

Maybe we could use format instead of type, if it exists?

**Expected result**

Warnings should display the correct information. 

**Actual result**

Warnings show missleading information.

**Steps to reproduce**

Go to the Service creation form.

**Troubleshooting**
