### ISSUE TITLE
BUG: Mounting a multi-context kubeconfig file through the kubeconfigID feature only mounts the current context

### ISSUE THREAD

**Issue by KaiReichart** [kyma-project/busola#1436]
**Description**

We are trying to mount a multi-context kubeconfig file into busola via the kubeconfigID feature.

Uploading the kubeconfig to busola via the file-upload tool works as expected. However, using the kubeconfigID feature
to load the kubeconfig from a hosting server only imports the current context.

Busola version: build from latest main commit

**Expected result**

- Each cluster from the multi-context file should be imported

**Actual result**

- Current-Context is loaded correctly
- Nothing else is imported

**Steps to reproduce**

- Have a multi-context kubeconfig file on a server
- use the kubeconfigID feature to load the file

**Troubleshooting**

- tried with and without active context in the file
- tried uploading it manually (this worked)
- tried redeploying the whole busola installation

Sample (redacted) multicontext file:
```
apiVersion: v1
kind: Config
clusters:
    - cluster:
        server: <<SERVER>>
        certificate-authority-data: <<CA>>
      name: shoot--dev--ps11-kyma-dev
    - cluster:
        server: <<SERVER>>
        certificate-authority-data: <<CA>>
      name: shoot--dev--osc-kafka01
contexts:
    - name: shoot--dev--ps11-kyma-dev
      context:
        cluster: shoot--dev--ps11-kyma-dev
        user: shoot--dev--ps11-kyma-dev-token
    - name: shoot--dev--osc-kafka01
      context:
        cluster: shoot--dev--osc-kafka01
        user: shoot--dev--osc-kafka01-token
current-context: shoot--dev--ps11-kyma-dev
users:
    - name: shoot--dev--ps11-kyma-dev-token
      user:
        token:  <<TOKEN>>
    - name: shoot--dev--osc-kafka01-token
      user:
        token: <<TOKEN>>
```
