### ISSUE TITLE
Unify translations format for object's elements

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1569]
**Description**
Depending on the widget, using translations for the object's elements is confusing.

**Actual result**
When creating a [Pizza resource](https://github.com/kyma-project/busola/blob/main/examples/pizzas/pizzas-configmap.yaml) via Form and adding Toppings, there aren't translations for `name`, `price` and `quantity`, although there are similar translations in the config map.
```yaml
  translations: |
    en:
      name: Pizza
      category: Lunch
      spec.description: Description
      spec.state: State
      spec.realization: Realization
      spec.paymentMethod: Payment Method
      spec.sauce: Sauce
      spec.toppings: Toppings
      topping.name: Name
      topping.price: Price
      topping.quantity: Quantity
```

In the screen below, we can see that those elements aren't translated
![image](https://user-images.githubusercontent.com/56163767/177752694-11f4fc1b-a8f0-456a-a2c2-94eda411c7fb.png)

If I want to have translated elements I need to add other properties to the `translations` yaml which are very similar to the ones that are already there.

```yaml
      spec.toppings: Toppings
      spec.toppings.name: Name
      spec.toppings.quantity: Quantity
      spec.toppings.price: Price
 ```
![image](https://user-images.githubusercontent.com/56163767/177753555-29671b31-a897-40fc-9482-381452b908a6.png)

It forces a user to declare similar things twice which can be very confusing. The reason why it currently behaves like that is that we use `topping.price` etc. as the children of the `Table` widget. We should unify that to not translate the same thing multiple times.
