### ISSUE TITLE
Improve Certificate status badge

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1645]
**Description**

**Reasons**

This is beautiful and all, but I suppose it would be better to show `type` from `status` field with that `message` as a tooltip.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/10504661/180432788-20edc93f-3766-46a7-9787-c185fa8c672b.png">

```yaml
...
status:
  conditions:
    - lastTransitionTime: '2022-07-15T15:19:46Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: 'True'
      type: Ready
  notAfter: '2022-10-13T15:19:46Z'
  notBefore: '2022-07-15T15:19:46Z'
  renewalTime: '2022-09-13T15:19:46Z'
  revision: 1
```
