### ISSUE TITLE
Edit Modal for functions doesnt read git source data for existing function

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#1751]
**Description**

**Expected result**

When opening edit modal for an existing git sourced function the source repo, basedir and git reference should contain values stored in the function spec

**Actual result**

When opening edit modal for an existing git sourced function the source repo, basedir and git reference contain default init values

**Steps to reproduce**

1. Create a git sourced function
2. Go to list view and hit edit action on the list item to see that  source repo, basedir and git reference are visible in the spec
3. Go to details view and observe the reference and basedir are filled corretly
![Screenshot 2022-08-12 at 12 05 22](https://user-images.githubusercontent.com/6783567/184332779-c26cfd34-17cf-49ed-8a55-9643327a25c5.png)
4. Open edit modal to see that source repo is empty;  basedir and git reference contain default values as if the modal was in creation mode

![Screenshot 2022-08-12 at 12 07 40](https://user-images.githubusercontent.com/6783567/184333085-3e430b3f-bed6-404c-88d5-e000bf80a3f7.png)

**Troubleshooting**

You can fetch the function via kubectl using both api versions. The source repo information is there

`kubectl get Function.v1alpha1.serverless.kyma-project.io orders-function -oyaml`
```yaml
spec:
  ...
  baseDir: /orders-function
  reference: master
  source: sample-lambda
  type: git
  ...
```

`kubectl get Function orders-function -oyaml`
```yaml
spec:
  ...
  source:
    gitRepository:
      baseDir: /orders-function
      reference: master
      url: https://github.com/kwiatekus/sample-lambda.git
      ...
```
**Related**
#1453
