### ISSUE TITLE
EXT: Cannot use Panel widget as a child of the Table's collapsible section

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1789]
**Description**
I would like to use a Panel widget as a child of the Table's collapsible section but the values are not displayed.
My Table widget:

```json
      {
        "widget": "Table",
        "source": "spec.tcp",
        "name": "TCP",
        "visibility": "$exists(*)",
        "collapsible": [
          {
            "source": "$item.route", "name": "Routes", "widget": "Table",
            "children": [
              {
                "source": "$item.destination", "name": "Destination", "widget": "Panel", "children": [  // bug
                  {
                    "source": "$item.host", "name": "Host"
                  },
                  {
                      "source": "$parent.subset", "name": "Subset"
                  },
                  {
                    "source": "$parent.port.number", "name": "Port"
                  },
                ] 
              },
              {
                "source": "$item.weight", "name": "Weight"
              }
            ]
          }
        ],
```

The TCP part of the YAML:
```yaml
  tcp:
    - match:
        - port: 22
          sourceLabels:
            test: test
        - port: 23
          sourceLabels:
            test: test
      route:
        - destination:
            host: test
            port:
              number: 11
          weight: 3
```

Values in the Panel aren't displayed:
![image](https://user-images.githubusercontent.com/56163767/186404438-e9ccee31-434c-4279-b9a6-5447d6d49254.png)

I tried to use many ways to get those values by manipulating the `source` property in both Panel widget and it's children.
