### ISSUE TITLE
Bug Upload YAML: Grey/White frozen background if resource name starts with "{" 

### ISSUE THREAD

**Issue by Prarthana29** [kyma-project/busola#1896]
**Description**

When we use the Upload YAML button in Kyma and paste the YAML with the resource name start with "{" the screen freezes with the grey background

Kyma on SAP BTP
Kubernetes: v1.23.9
Kyma: 2.6.3
Browser: Chrome, Version 105.0.5195.125 (Official Build) (x86_64)

**Expected result**
Error message that suggests as an incorrect name

**Actual result**
Grey frozen screen

**Steps to reproduce**

The below specs copy-pasted in the UI Upload editor space results in the issue
```
apiVersion: v1
kind: Service
metadata:
  name: {}
spec:
  selector:
    app: hello-world
  ports:
    - port: 8080
      targetPort: 8080
```

**Troubleshooting**
