### ISSUE TITLE
Support for ENVs injected via secrets or configmaps in the function UI 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#194]
**Description**
Function ENVs injected via secrets or configmaps are not visible in the busola UI 

**Expected result**

User should see envs that are used from secrets or config maps

**Actual result**

Function UI in busola supports only envs with value. Envs with `valueFrom` are skipped
```
  env:
  - name: FOO
    valueFrom:
      secretKeyRef:
        key: foo
        name: test-secret
  - name: ABC
    valueFrom:
      configMapKeyRef:
        key: abc
        name: test-config
  - name: HAKUNA
    value: MATATA
 ```

**Steps to reproduce**

1. Have a kyma cluster running and accesible via CLI and Busola UI

2. Prepare test config map and test secret in the default namespace
```
kubectl create configmap test-config --from-literal abc="xyz" -n default
kubectl create secret generic -n default --from-literal foo="bar" test-secret
```
3. Initialise a simple function via kyma CLI (make sure you use latest version)
```
kyma init function --name test --namespace default --runtime nodejs14
```
4. Modify config.yaml
```
name: test
namespace: default
runtime: nodejs14
source:
  sourceType: inline
env:
  - name: FOO
    valueFrom:
      secretKeyRef:
        name: test-secret
        key: foo
  - name: ABC
    valueFrom:
      configMapKeyRef:
        name: test-config
        key: abc
  - name: HAKUNA
    value: MATATA
```
5. Modify handler.js
```
module.exports = {
    main: function (event, context) {
        return process.env["FOO"] + process.env["ABC"];
    }
}
```
6. Apply function 
```
kyma apply function 
```

7. Navigate to busola UI and show the function

![Screen Shot 2021-06-08 at 11 36 18](https://user-images.githubusercontent.com/6783567/121162119-ed0cad00-c84d-11eb-8178-e12e4bf81087.png)

Observe that ENVs injected from config map and secret are not shown

8. (Optional) Expose the function to see that the env values are injected (they are part of the returned value )

**Hints**

This works on console.
It was introduced probably after creating busola repository.
Please have a look at this [PR](https://github.com/kyma-project/console/pull/2098/files) which introduced it to console (Maybe it is easy to port the changes to busola)
