### ISSUE TITLE
EXT: Presets in Functions don't work

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#2031]
**Description**
The Functions form presets created by the extensibility don't work. It successfully pastes the runtime information in the yaml but the source code of the function is missing. It is probably caused by the `visibility` flag that uses `sourceType` var. 

**Expected result**
Source code of the function's preset should be changed succesfully.

**Actual result**
When clicking on one of the presets (Node or Python) the runtime is changed, but source code is missing.

**Steps to reproduce**
- Go to the function's create form that uses extensibility. Go to `YAML`.
- Choose the preset you like. 
- New runtime value should appear, but the source object is empty.

**Troubleshooting**
It is probably caused by the `visibility` flag that uses `sourceType` var. 

Presets property:
```yaml
  presets: |-
    - name: Node.js Function
      default: true
      value:
        spec:
          runtime: nodejs14
          source:
            inline:
              source: |-
                module.exports = {
                  main: async function (event, context) {
                    const message = `Hello World`
                      + ` from the Kyma Function ${context["function-name"]}`
                      + ` running on ${context.runtime}!`;
                    console.log(message);
                    return message;
                  }
                }
    - name: Python Function
      value:
        spec:
          runtime: python39
          source:
            inline:
              source: |-
                def main(event, context):
                    message = "Hello World from the Kyma Function "+context['function-name']+" running on "+context['runtime']+ "!";
                    print(message)
                    return message
```

The piece of the code responsible for CodeEditor that causes the problem:
```yaml
    - path: spec.source.inline
      visibility: $sourceType = 'Inline' # the cause
      children:
        - path: source
          widget: CodeEditor
          language: '$contains($root.spec.runtime, "node") ? "javascript" : "python"'
        - path: dependencies
          widget: CodeEditor
          language: '$contains($root.spec.runtime, "node") ? "javascript" : "plaintext"'
```
