### ISSUE TITLE
Internal incident: functions/apirules view broken

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#2072]
**Description**

Newest format of API Rule breaks the API Rules list & Function details (where API Rules list is embedded).

**Reproduction**

Deploy the following apirule:

```yaml
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
    namespace: default
    name: fx
spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    host: fx.nkyma.kyma-prow.shoot.live.k8s-hana.ondemand.com
    rules:
    - accessStrategies:
        - handler: noop
      methods:
        - POST
        - GET
      path: /.*
```

**Fix**

Update `prod` environment to `fdc66fb6` version (same as [stage](https://github.tools.sap/kyma/busola-deploy/blob/stage/stage/main.tf)).

**Attachments**

[Customer issue](https://support.wdf.sap.corp/sap(bD1lbiZjPTAwMSZkPW1pbiZpPTE=)/bc/bsp/sap/crm_ui_start/default.htm?saprole=ZCSSINTPROCE&crm-object-type=CRM_SRQM_INCIDENT&crm-object-keyname=OBJECT_GUID&crm-object-value=0090FAE68E5E1EED9AAFB10D9B7DA0CD)

[Recording](https://sap.sharepoint.com/teams/NationalAutomotiveAlliance/_layouts/15/stream.aspx?id=%2Fteams%2FNationalAutomotiveAlliance%2FShared%20Documents%2FSpeedboat%2F01%5FDISMANTLER%20COCKPIT%2FVideos%2F2022%2D11%2D21%5F10%2D22%2D21%2Emp4&ga=1)
