### ISSUE TITLE
choosing a preset does not reset vars

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#2145]
**Description**

In extensibility, when choosing a preset that would influence as `dynamicValue` of a `var` field, it does not reset the variables, and as such does not change the value of the variable field.

**Expected result**

`dynamicValue` should be recalculated.

**Actual result**

Variable fields are unchanged.

**Steps to reproduce**

For example:
set the presets to:
```
- name: preset 1
  value:
    spec:
      foo: true
- name: preset 2
  value:
    spec:
      foo: false
```
and the variable to:
```
- var: something
  type: string
  dynamicValue: spec.foo ? 'enabled' : 'disabled'
```
Choose any preset. Value of `var: something` field should change to either `enabled` or `disabled`.
