### ISSUE TITLE
Improve automation in extensibility

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#2148]
Add extra features for automation:
1. add an `init` trigger (that happens on initial open)
2. allow multiple triggers in one rule (for example `$root.foo,bar` - would catch both `$root.foo` and `bar`)
3. add triggers in presets (#2249)
4. add match/value subscriptions, to replace multi-level conditions in jsonata for example an array instead of jsonata string:
```
subscribe:
  foo:
    - match: $foo === 'bar'
      value: matched value 1
    - match: $foo === 'baz'
      value: a different value
```
this could be used as an alternative to:
```
subscribe:
  foo: |
    $foo === 'bar' ? 'matched value 1' :
    $foo === 'baz' ? 'a different value' :
    ''
```
(mostly useful in more complex cases than this example)
