### ISSUE TITLE
HPA don't show up on Deployment pages

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2179]
**Description**

The deployment page does not show up HPA

**Expected result**

HPA should be listed as resources on Deployment pages

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by akucharska** [comment]
It works as intended. We show HPA that has:
```
spec:
  scaleTargetRef:
    kind: Deployment
    name: {DEPLOYMENT_NAME}
```

If a function manages deployment and HPA then we won't show the former on the deployment page.
