### ISSUE TITLE
simple/advanced flags don't work for children

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#2195]
**Steps to reproduce**

For an example form section of a spec:
```yaml
- path: spec.foo
  simple: true
  children:
    - path: bar
      simple: true
    - path: baz
```

**Expected result**

only `spec.foo.bar` should show up in simple and both `spec.foo.bar` and `spec.foo.baz` should be in advanced

**Actual result**

both show up in simple form
