### ISSUE TITLE
EXT: Not required parent, but required child doesn't work

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#2272]
**Description**
In some cases in from child is required, but parent isn't required, for example Sidecars -> Egress -> Port.

**Reasons**
Form doesn't allow to create Valid YAML from Sidecars docs.
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: istio-config
spec:
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
```
We remove required flag from CM, needs to be back after resolving issue.
https://github.com/kyma-project/kyma-dashboard/pull/70

**Attachments**
![image](https://user-images.githubusercontent.com/46759954/211773016-c59cdbfb-446e-419f-832a-0e8ff93043dc.png)
![image](https://user-images.githubusercontent.com/46759954/211773060-c0d37698-85f6-4602-9584-01e93bf0b91b.png)
