### ISSUE TITLE
kube-public/busola-config does not patch PROTECTED_RESOURCES

### ISSUE THREAD

**Issue by jalibu** [kyma-project/busola#2339]
**Description**

1. I have the following config map in kube-public namespace
  ```
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: busola-config
    namespace: kube-public
  data:
    config: |
      config:
        features:
          PROTECTED_RESOURCES:
            isEnabled: true
            config:
              resources:
                - match:
                    $.metadata.labels['app.kubernetes.io/created-by']: JanSuperman
                  message: 'Locked resource. Do not change. This resource is managed by my super power.'
        
  ```
2. I can confirm in the Developer Tools Net-tab that the config map is loaded with the contents above
3. Namespaces with the tag `app.kubernetes.io/created-by=JanSuperman` don't have the Lock symbol.
4. Other namespaces (like the managed by reconciler) still have it
