### ISSUE TITLE
kube-public/busola-config EXTERNAL_NODES are rendered with wrong indent

### ISSUE THREAD

**Issue by jalibu** [kyma-project/busola#2341]
**Description**

1. Create a CM with following content in kube-public namespace:
  ```
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: busola-config
      namespace: kube-public
    data:
      config: |
        config:
          features:
            EXTERNAL_NODES:
              stage: SECONDARY
              nodes:
                - category: External Links
                  icon: course-book
                  children:
                    - label: Example 1
                      link: https://example1.com
                    - label: Example 2
                      link: https://example2.com

  ```
2. Rendered result:
 
![image](https://user-images.githubusercontent.com/25933231/216758913-b9147166-9f8a-4550-82b0-828a2cea4cf9.png)
