### ISSUE TITLE
String generation in `resource` mixes strings up

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/busola#2372]
**Description**

For Eventing, in our [Busola Extension](https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/controller/templates/busola-extension.yaml) we want to [create a dropdown](https://github.com/kyma-project/kyma/pull/16922/files) that creates a string (the `sink`) from a substring (the `service`) so we don't have to display/manage both and streamline the creation of Subscriptions.

We defined the field like this
```yaml
- path: spec.sink
      name: spec.sink
      widget: Resource
      resource:
        kind: Service
        version: v1
        scope: namespace
      simple: true
      placeholder: placeholder.sink
      trigger: [sink]
      subscribe:
        sink: '"http://" & spec.sink & "." & $root.metadata.namespace & ".svc.cluster.local"'
```

And so, if you click on one of the options (`service`s): 
![image](https://user-images.githubusercontent.com/58187735/222435854-fd3bf46d-7491-4444-8aa8-0985d7a2900e.png)
it will create the `sink`:
![image](https://user-images.githubusercontent.com/58187735/222436063-52452427-6534-4ef0-86c3-e79dc84465bd.png)
while this works for the better part.
![image](https://user-images.githubusercontent.com/58187735/222436276-fd9b02fa-815a-4e66-98be-35db7cf7159c.png)
sometimes, this is getting mixed up,![image](https://user-images.githubusercontent.com/58187735/222436418-b93c980c-3c89-435c-bd20-ca569c8381d1.png)
 Especially if you move between simple/advanced and yaml.

**Expected result**

nice sink

**Actual result**

messed up sink
**Steps to reproduce**

**Troubleshooting**
