### ISSUE TITLE
Extensibility: id/ref

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#2400]
Support assigning ids to widgets and referencing them in other widgets.
Consider the format:
1. string - `namespace/name/id` eg. `ref: kube-public/qqqs/foo` (could fall back to just `id` if within the same extension)
2. object: eg.
```
ref:
  namespace: kube-public
  name: qqqs
  id: foo
```
3. look into the possibility of adapting the existing `$ref` feature of json-schema (this would replace the currently included `ReferencingHandler` which isn't really used - except for the extension edit form, but that one has it's own config)

**Comment by qbalukom** [comment]
take a look at `ReferencingHandler` from `ui-schema` for potential inspiration

**Comment by qbalukom** [comment]
this should be implemented both for form and display widgets (possibly display as a separate)

**Comment by qbalukom** [comment]
```
library:
  form:
    - id: inout-rules
      widget: GenericList
      children:
        - fgfd gd
  display:

resource:
  form:
   - path: spec.in-rules
     id: in-rules
     ref: inout-rules
   - path: spec.out-rules
     id: out-rules
     ref: in-rules


wizard:
  steps:
    form:
      - ref: kube-public/dupas.example.com/in-rules
      - ref: kube-public/dupas.example.com/out-rules
```
