### ISSUE TITLE
Allow configuring function's runtime annotations from UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#2736]
**Description**

Allow configuring function's runtime annotations from UI

**Reasons**

UI users should also be able to manage annotations
Missing part of https://github.com/kyma-project/kyma/issues/16232

**Attachments**

```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: node
    name: node
    namespace: default
spec:
    labels:
        label1: value1
    annotations:
        annotation2: value2
        ....
```
