### ISSUE TITLE
Hana Cloud creation and manipulation is only possible in YAML

### ISSUE THREAD

**Issue by halamix2** [kyma-project/busola#2869]
**Description**

* Creating Hana Cloud Service Instance resource is not possible in the form view
* After creating Hana instance with the YAML input, clicking edit->Form displays `Something went wrong. We restored the initial form for you.` with broken `go back` button.

**Expected result**

I should be able to create Hana using form view

```yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: hana
  labels:
    app.kubernetes.io/name: hana
  annotations: {}
  namespace: default
spec:
  serviceOfferingName: hana-cloud
  servicePlanName: hana
  externalName: hana
  parameters:
    data:
      memory: 30
      vcpu: 2
      whitelistIPs: 
        - 0.0.0.0/0
      generateSystemPassword: true
      edition: "cloud"
```

**Actual result**
I'm unable to create Hana using form view.
Editing using form view breaks the edit view until I select another resource and switch back to yaml view.
The "Go back" button does not work

```yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: hana
  labels:
    app.kubernetes.io/name: hana
  annotations: {}
  namespace: default
spec:
  serviceInstanceName: hana-cloud
  externalName: hana
  parameters: |
    data:
      edition: cloud
      generateSystemPassword: true
      memory: 32
      vcpu: 2
      whitelistIPs:
      - 0.0.0.0/0
```
**Steps to reproduce**

* create Hana instance using the yaml from expected results
* click edit -> form view

**Troubleshooting**
* Form view expects parameters to be a string
