### ISSUE TITLE
Allow adding description for widget FormGroup

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2893]
**Description**
The user wants to add description for the FormGroup .
It should allow using links
`{{[Sth]([https://link.com)}}]`

**Reasons**

**Attachments**
```
- widget: FormGroup
    path: integration
    description: Integration with service mesh. Currently, only Istio service mesh is supported. The only acceptable value is 'enabled'. If it is set, the Transparent proxy components will be integrated in the mesh, otherwise they will be exclusively removed from the mesh.
    children:
              - path: defaultInstanceName
                description: Name of the default destination service instance to be used when 'destinationServiceInstanceName' is not provided in the Destination Custom Resource spec.
              - path: connectionTimeoutSeconds
                description: The connect timeout used when getting access tokens and destination service clients. [1, 60] seconds allowed.
              - path: readTimeoutSeconds
                description: The read timeout used when getting access tokens and destination service clients. [1, 60] seconds allowed.
              - widget: FormGroup
                path: serviceMesh
                placeholder: Integration with service mesh. Currently, only Istio service mesh is supported. The only acceptable value is 'enabled'. If it is set, the Transparent proxy components will be integrated in the mesh, otherwise they will be exclusively removed from the mesh.
                children:
                  - widget: FormGroup
                    path: istio
                    children:
                      - path: istio-injection
                        type: boolean
                        name: Istio injection
```
