### ISSUE TITLE
UI created with Busola extensibility reports 404 when `urlPath` does not match resource name

### ISSUE THREAD

**Issue by barchw** [kyma-project/busola#2927]
**Description**

When providing a UI for `telemetries.telemetry.istio.io` goats wanted to make sure that the path does not conflict with `telemetry-manager` `telemetry` resource. To achieve this the `urlPath` was utilised, configuring it to `istiotelemetries`. Hovewer, switching the parameter to anything other that `telemetries` results in a `404 not found` error during resource creation in Busola.

**Expected result**

The `urlPath` parameter works with any value.

**Actual result**

The `urlPath` parameter works only with the resource plural form.

**Steps to reproduce**

1. Create a UI with Busola extensibility for `telemetries.telemetry.istio.io` resource. Configure the general section as follows:
```yaml
resource:
  kind: Telemetry
  group: telemetry.istio.io
  version: v1alpha1
urlPath: istiotelemetries
category: Istio
name: Telemetries
scope: namespace
description: >-
  {{[Telemetry]([https://istio.io/latest/docs/reference/config/telemetry)}}](https://istio.io/latest/docs/reference/config/telemetry)%7D%7D)
  defines how the telemetry is generated for workloads within a mesh.
```
2. Try to create the resource in it's tab in Busola.

**Troubleshooting**
