### ISSUE TITLE
Handle pure integers values when populated via form text widget into a CR field of type string

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#2944]
**Description**

Please handle pure integers values when populated via form text widget into a CR field of type string.
When an integer value was provided by user into string type field, decorate the rendered value with quotes, i.e

`1 -> '1'`

Currently the `Text` widget doesnt detect that an integer value is provided into string property

![Screenshot 2024-05-27 at 15 35 11](https://github.com/kyma-project/busola/assets/6783567/8bca70f9-4b28-4d84-93e9-448774e3a760)
![Screenshot 2024-05-27 at 15 35 04](https://github.com/kyma-project/busola/assets/6783567/5993df84-396c-4cc9-954b-f51207c946d4)

And when I try to overcome the problem by adding quotation characters into the form, the yaml is rendered as follows:
![Screenshot 2024-05-27 at 15 35 36](https://github.com/kyma-project/busola/assets/6783567/66f42774-e7d4-45f5-9840-5b70a767d2c4)

  
 

**Reasons**

Kubernetes allows putting an integer value into a string field, but requires decorating the value with quotation. It would be super awesome if busola was able to detect such scenarios and provide value in quotations:

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Serverless
...
spec:
  defaultBuildJobPreset: slow
  defaultRuntimePodPreset: S
  dockerRegistry:
    enableInternal: true
  functionBuildMaxSimultaneousJobs: '1' # <-- this spec field is of type string but controller expects integer value
```

**Workaround**

Go to YAML tab and manually edit the value using an integer decorated with quotation.

**Related issues**
https://github.com/kyma-project/serverless/issues/993
