### ISSUE TITLE
BUG: Memory requests and Limits graphs should not sum values from Resource Quotas but take the lower one

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2988]
If there is more than one resource quota on a namespace then the lower value should be used in graphs

![Image](https://github.com/kyma-project/busola/assets/20790348/7d9f0397-2533-4e53-824d-2efa188b3535)

**Comment by dbadura** [comment]
## Taking the lowest resource

Having 2 Resource Quotas:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
spec:
  hard:
    cpu: "1000"
    memory: 2Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["high"]
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
spec:
  hard:
    cpu: "1000"
    memory: 2Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["low"]

```

and applying such pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-container
  name: test-container
spec:
  priorityClassName: low
  containers:
  - name: test-container
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 1Gi
```

Will trigger only one quota:
```
→ kubectl get quota
NAME                  AGE   REQUEST                                       LIMIT
pods-high-burstable   21s   cpu: 0/1k, memory: 0/2Gi, pods: 0/10          
pods-low-burstable    38s   cpu: 100m/1k, memory: 100Mi/2Gi, pods: 1/10 
```

It doesn't make sense to get mnimum value from resource quota.

## Taking the sum of resources
The same situation applies to sum of resources: https://stackoverflow.com/questions/69127848/what-happens-if-more-than-one-resourcequota-is-enabled-per-namespace.
