### ISSUE TITLE
ClusterPreview shows only one `scope`, even if there are multiple configured in the kubeconfig

### ISSUE THREAD

**Issue by v0lkc** [kyma-project/busola#3055]
**Description**

The review page of the cluster wizard only displays one oidc scope, even if multiple scopes are configured in the kubeconfig. The configuration may look like this:

```
users:
- name: xsuaa
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-use-access-token
      - --oidc-issuer-url=...
      - --oidc-client-id=...
      - --oidc-client-secret=...
      - --oidc-extra-scope=scope_a
      - --oidc-extra-scope=scope_b
      - --oidc-extra-scope=scope_c
```

It would only display `scope_a`

**Expected result**

`scope_a`, `scope_b` and `scope_c` should be displayed.

**Actual result**

Only `scope_a` is shown.

**Steps to reproduce**

**Troubleshooting**
