### ISSUE TITLE
External links in static extension

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#3112]
**Description**
I couldn't find any example of how to add an external link using the static extension. I created my own, but it is now working:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: pb-links
  namespace: kube-public
  labels:
    app.kubernetes.io/name: pb-links
    busola.io/extension: statics
    busola.io/extension-version: '0.5'
data:
  general: |-
    externalNodes:
      - category: My Category
        icon: course-book
        scope: cluster
        children:
          - label: Example Node Label
            link: 'https://github.com/kyma-project/busola'
```
Please add one working example that people can copy&paste.
