### ISSUE TITLE
UI Views for api exposure

### ISSUE THREAD

**Issue by strekm** [kyma-project/busola#320]
**Description**

Implement set of forms to add / edit gardener [dns](https://github.com/gardener/external-dns-management) and [cert](https://github.com/gardener/cert-management) management CR.

User should be able to create DNSProvider:

```
cat << EOF | kubectl apply -f -
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: aws
  namespace: default
spec:
  type: aws-route53
  secretRef:
    name: aws-credentials
  domains:
    include:
    # this must be replaced with a (sub)domain of the hosted zone
    - my.own.domain.com
EOF
```
- type - predefined list of supported providers, 
- reference to secret with credentials (`aws-credentials`) - secret should be created before user tries to create DNSProvider. This field can be already populated from secrets on a cluster. 
- domains - list of domains, user needs to provide this information, cannot be calculated

Next step would be to create DNSEntry:

```
cat << EOF | kubectl apply -f -
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: mydnsentry
  namespace: default
spec:
  dnsName: "myentry.my-own-domain.com"
  ttl: 600
  targets:
  - 1.2.3.4
EOF
```
- dnsName - user provided, partially can be calculated from DNSProvider domain (in first iteration can be simply provided by an user)
- ttl - user provided, values can be sugested
- targets - list of IP addresses, can be selected from all service of type LoadBalancer (in case of kyma it's IP address of istio ingress gateway but i would leave user flexibility to choose from svc type LB)

Creation of Issuer:

```
apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: issuer-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: some.user@mydomain.com
    autoRegistration: true
    # with 'autoRegistration: true' a new account will be created if the secretRef is not existing
    privateKeySecretRef:
      name: issuer-staging-secret
      namespace: default
```

- server - user provided (i'm not sure if we want to suggest anything here)
- autoRegistration - checkbox. depending of whether it's checked or not we might handle secret reference in different way
- secret reference - in case user checked `autoRegistration` then he can provide name and namespace (we can suggest some default value e.g. issuer-name-secret). if user did not check `autoRegistration` then we can list existing secrets for user to choose from

Certificate:

```
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-simple
  namespace: default
spec:
  commonName: cert1.mydomain.com
  dnsNames:
  - cert1-foo.mydomain.com
  - cert1-bar.mydomain.com
  # if issuer is not specified, the default issuer is used
  issuerRef:
    name: issuer-staging
```

- commonName - partially can be calculated from existing domains
- dnsNames - list, partially can be calculated
- issuer - reference to existing issues    

**Reasons**

Simplify steps which customer needs to execute to expose his workload. 

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/11839
depends on: https://github.com/kyma-project/kyma/issues/11828
