### ISSUE TITLE
Login error when one or more `--oidc-extra-scope` args are present in the kubeconfig

### ISSUE THREAD

**Issue by v0lkc** [kyma-project/busola#3288]
**Description**

When a kubeconfig file contains one or more `--oidc-extra-scope` parameters, Busola stops sending the "openid" scope, resulting in a login error. The error message returned is: `Login error: ErrorResponse: Invalid token does not contain resource id (openid)`. The "openid" scope is expected to always be sent, regardless of any additional scopes provided.

**Expected result**

No error

**Actual result**

![image](https://github.com/user-attachments/assets/764303e5-9703-437e-bead-51a92db4b932)

**Steps to reproduce**

```yaml
apiVersion: v1
clusters:
   ...
users:
- name: xsuaa
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://...
      - --oidc-client-id=some-id
      - --oidc-client-secret=a-secret
      - --oidc-extra-scope=first-scope
      - --oidc-extra-scope=second-scope
      command: kubectl
```

**Troubleshooting**
