### ISSUE TITLE
Camel Cased Every Word In Module View

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/busola#3356]
**Description**

I Observed That Every Fields Value Displayed In The Overview Of The Module Is Camel Cased. For Example, For The Serverless Module Has Field `Eventing Endpoint` With Value `http://eventing-publisher-proxy.kyma-system.svc.cluster.local/publish` But It's Displayed As `http://Eventing-Publisher-Proxy.Kyma-System.Svc.Cluster.Local/Publish`. Screenshots:

<img width="1057" alt="Screenshot 2024-09-23 at 13 42 09" src="https://github.com/user-attachments/assets/f54b70f8-916c-419f-804f-c27bcb31b579">

Resource Status:

```yaml
status:
  conditions:
    - lastTransitionTime: '2024-09-23T09:49:00Z'
      message: Configuration ready
      reason: Configured
      status: 'True'
      type: Configured
    - lastTransitionTime: '2024-09-23T09:49:37Z'
      message: Serverless installed
      reason: Installed
      status: 'True'
      type: Installed
  defaultBuildJobPreset: normal
  defaultRuntimePodPreset: L
  dockerRegistry: internal
  eventingEndpoint: http://eventing-publisher-proxy.kyma-system.svc.cluster.local/publish
  served: 'True'
  state: Ready
```

**Expected result**

The displayed value should reflect the real state and the camel case should be an additional, optional configuration.
