### ISSUE TITLE
Dynamic value of the `readOnly` field for FormGroup children

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/busola#3358]
**Description**

It's not possible to make fields not operational dynamically. Right now we achieve that using the `visibility` field but we prefer to inform users that if the `enabled` field is false then other fields are still there but are not operational.

It would be nice to have a feature allowing developers to disable a form field but not hide it. In this case when the field is disabled (for example) turnes gray, the value can't be changed, bu it's still displaying the latest value.

**Reasons**

In our case we want to allow users to edit fields `gateway` and `host` only when the `enabled` field is true. In other cases values for these fields should be displayed but not possible to edit/change them. 

Our module allows both configurations:

```yaml
spec:
  externalAccess:
    enabled: true
    gateway: kyma-system/fs-super-gateway
    host: super-registry.fb7b356.stage.kyma.ondemand.com
```

and

```yaml
spec:
  externalAccess:
    enabled: false
    gateway: kyma-system/fs-super-gateway
    host: super-registry.fb7b356.stage.kyma.ondemand.com
```

so we should not hide the `gateway` and the `host` in the form view when the `enabled` field is false

**Attachments**

Our solution is described [here](https://github.com/kyma-project/docker-registry/pull/204)
