### ISSUE TITLE
Deep links in overview section are hidden and truncated

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/busola#3438]
**Description**

The links functionality in the different overview sections is very hidden (behind 3 dots) and even if expanded, the links are all truncated:
<img width="1222" alt="Screenshot 2024-10-30 at 14 14 08" src="https://github.com/user-attachments/assets/73f45e7c-260f-4f66-b57d-114ee4204a7f">

The links are configured via busola extensions mechanism like:
```yaml
injections: |-
    - name: "Logs for namespace"
      source: "'Discover Logs in SAP Cloud Logging'"
      link: "$prepareUrl($string('https://') & $base64decode($string($clsSecret().data.'dashboards-endpoint')) & '/app/discover?security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:5000),time:(from:now-1d,to:now))&_a=(columns:!(kubernetes.pod_name,kubernetes.container_name,trace_id,log),filters:!((query:(match_phrase:(kubernetes.namespace_name:{name})))),index:maintained-by-perfx_kyma-content-package_index-pattern-logs-json-kyma)',
        {'name': $embedResource.metadata.name}
      )"
      widget: ExternalLink
      type: button
      copyable: false
      targets:
        - slot: details-header
          location: Namespaces
```

**Expected result**
The links are easy to find and the full text is readable

**Actual result**
I'm not aware that deep links are available. When I know where they are, I cannot easily differentiate them

**Steps to reproduce**

**Troubleshooting**
