### ISSUE TITLE
Do not show deployment as healthy if the replica creation failed (i.e because of warden)

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#3472]
#### Expected
As a namespace administrator I need to see more prominently errors related to deployments that fail to create their replicas (i.e. because of warden blocking the pod admission)

#### Actual
Currently, both on namespace overview page and deployment list, that deployment appears healthy, even though there are no pods because of `ReplicaFailure` condition

```
    - type: ReplicaFailure
      status: 'True'
      lastUpdateTime: '2024-11-12T09:59:39Z'
      lastTransitionTime: '2024-11-12T09:59:39Z'
      reason: FailedCreate
      message: >-
        admission webhook "validation.webhook.warden.kyma-project.io" denied the
        request: Pod images kennethreitz/httpbin:latest validation failed
```

Please note that `ReplicaFailure` condition is a negative one.. so if it's status is 'true' it means a problem.

#### How to reproduce
 1. Use dev environment, where new warden capabilities are enabled
 2. ensure warden label and annotations on a target namespace
```
  ...
  labels:
    ...
    namespaces.warden.kyma-project.io/validate: user
  annotations:
    namespaces.warden.kyma-project.io/notary-url: https://signing.repositories.cloud.sap
    namespaces.warden.kyma-project.io/strict-mode: 'true'
```
 3. Create a deployment in the target namespace from non-signed image, i.e `image: kennethreitz/httpbin:latest` 
 
 
![Image](https://github.com/user-attachments/assets/0f5a0c36-9373-40a9-91a7-0a3180a1050e)

![Image](https://github.com/user-attachments/assets/c2895532-8a77-42a1-a1f4-bb7c6820d465)

![Image](https://github.com/user-attachments/assets/2e63aa16-2fe6-4b7e-aff7-997ec1688fec)
