### ISSUE TITLE
Make Module CR navigable on module list also in case of modules operated with  `customResourcePolicy: Ignore`

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#3624]
**Description**

After adding docker-registry module with custom DockerRegistry CR via kyma cli (v3) 
`kyma@v3 alpha module add docker-registry -c experimental --some-custom-docker-registry.yaml`
I end up having a running module, but I cannot see the status representing this fact on the module list (see attachment). The module CR is also not navigable as the link is not there in the first column.

This stems from the fact that such installation mode doesnt leave a reference to Module CR in the Kyma CR status. Such case adds the module with the `customResourcePolicy: Ignore` and user is entirely responsible for managing lifecycle of that Module CR

```
    - channel: experimental
      customResourcePolicy: Ignore
      managed: true
      name: docker-registry
```

In such case we could take the best effort approach and try to find the Module CR, render link and status badge.

**Ideas**

In theory kyma module operators should allow for one module CRs, so there should be one instance only.
Busola could read the type information of the module CR from the ModuleTemplate CR and lookup all instances and take the first one.
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
...
  name: docker-registry-experimental
  namespace: kyma-system
...
spec:
  channel: experimental
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: DockerRegistry
```

**Reasons**
Enabling kyma modules with custom Module CR  from the beginning provides faster uptime for a module when comparing to enabling module with default CR and customising it post-installation. Adding the feature would improve user experience for such case and would make it consistent with experience users get when they enable modules with default module CR. 

**Attachments**

![Image](https://github.com/user-attachments/assets/93ae1a76-5add-4a7c-8bf4-87fa5df6e62b)
