### ISSUE TITLE
Parse `default` field for schema and auto populate in Form field

### ISSUE THREAD

**Issue by kevin-kho** [kyma-project/busola#3640]
**Description**

Currently, busola doesn't parse the `default` field when calling `useGetSchema`.

**Reasons**

We like to automatically populate default values when creating a resource within busola UI.

**Attachments**

Assume we have the following YAML snippet:
```
spec:
  properties:
    engineVersion:
      default: "7.0"
      enum:
        - "7.1"
        - "7.0"
        - 6.x
      type: string
```

`useGetSchema` will parse `enum` and `type` but fails to parse `default`.

We'd like to parse it and auto populate/set the field on the Form
