### ISSUE TITLE
Display available GPUs

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#3778]
**Description**
Provide number of available GPU in cluster node view and in cluster overview and on the details view, if value is presented.
You can take the information from node status (nvidia.com/gpu):
```
status:
  addresses:
  - address: shoot--kyma-stage--c-xxxxxxxx-gpu-z3-59846-4262c
    type: Hostname
  allocatable:
    cpu: 3920m
    ephemeral-storage: "78975464387"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 27597604Ki
    nvidia.com/gpu: "1"
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 81183660Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 28748580Ki
    nvidia.com/gpu: "1"
    pods: "110"

```

**Reasons**
GPU machines are available in Kyma clusters and people want to see the GPU capacity.
