### ISSUE TITLE
Status field does not render if body is not present

### ISSUE THREAD

**Issue by barchw** [kyma-project/busola#3913]
**Description**

When creating an extensibility configuration with the use of `status` field, the field will not render unless the `body` subfield is present.

For example:

```yaml
status:
  header:
    - name: status
      source: status.state
      widget: Badge
      description: status.description
      highlights:
        positive:
          - 'Ready'
        negative:
          - 'Error'
        critical:
          - 'Warning'
```

Will not render the field in the details view at all.

**Expected result**

The field is rendered even if only `headers` are present.

**Steps to reproduce**

Can be reproduced by using the following yaml of Istio CR ui:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-ui.operator.kyma-project.io
  namespace: kyma-system
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: istio-operator-default
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: dev
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    kyma-project.io/module: istio
data:
  details: |
    status:
      header:
        - name: status
          source: status.state
          widget: Badge
          description: status.description
          highlights:
            positive:
              - 'Ready'
            negative:
              - 'Error'
            critical:
              - 'Warning'
    body:
    - widget: Panel
      name: Configuration
      children:
        - source: spec.config.gatewayExternalTrafficPolicy
          name: config.gatewayExternalTrafficPolicy
          visibility: '$exists($value)'
        - source: spec.config.numTrustedProxies
          name: config.numTrustedProxies
          placeholder: '1'
        - source: spec.compatibilityMode
          name: compatibilityMode
          placeholder: 'false'
        - source: spec.config.telemetry.metrics.prometheusMerge
          name: config.prometheusMerge
          placeholder: 'false'

        - name: config.authorizers
          widget: Table
          source: spec.config.authorizers
          visibility: $exists($value)
          collapsibleTitle: "$item.name"
          collapsible:
            - name: config.authorizers.headers.inCheck.add
              # For some reason $each doesn't return an array that works with JoinedArray widget, when we have only one element. So in this case we return an Array with one element.
              source: '$count($keys(headers.inCheck.add)) = 1 ? $each(headers.inCheck.add, function($v, $k) {[$k & ":" & $v]}) : $each(headers.inCheck.add, function($v, $k) {$k & ":" & $v})'
              widget: JoinedArray
            - name: config.authorizers.headers.inCheck.include
              source: headers.inCheck.include
              widget: JoinedArray
            - name: config.authorizers.headers.toUpstream.onAllow
              source: headers.toUpstream.onAllow
              widget: JoinedArray
            - name: config.authorizers.headers.toDownstream.onAllow
              source: headers.toDownstream.onAllow
              widget: JoinedArray
            - name: config.authorizers.headers.toDownstream.onDeny
              source: headers.toDownstream.onDeny
              widget: JoinedArray
          children:
            - name: config.authorizers.service
              source: service
            - name: config.authorizers.port
              source: port

        - widget: Panel
          name: Pilot
          visibility: '$exists(spec.components.pilot.k8s.hpaSpec.minReplicas) or $exists(spec.components.pilot.k8s.hpaSpec.maxReplicas) or $exists(spec.components.pilot.k8s.strategy.rollingUpdate.maxSurge) or $exists(spec.components.pilot.k8s.strategy.rollingUpdate.maxUnavailable) or $exists(spec.components.pilot.k8s.resources.limits.cpu) or $exists(spec.components.pilot.k8s.resources.limits.memory) or $exists(spec.components.pilot.k8s.resources.requests.cpu) or $exists(spec.components.pilot.k8s.resources.requests.memory)'
          children:
          - source: spec.components.pilot.k8s.hpaSpec.minReplicas
            name: k8s.hpaSpec.minReplicas
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.hpaSpec.maxReplicas
            name: k8s.hpaSpec.maxReplicas
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.strategy.rollingUpdate.maxSurge
            name: k8s.strategy.rollingUpdate.maxSurge
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.strategy.rollingUpdate.maxUnavailable
            name: k8s.strategy.rollingUpdate.maxUnavailable
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.resources.limits.cpu
            name: k8s.resources.limits.cpu
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.resources.limits.memory
            name: k8s.resources.limits.memory
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.resources.requests.cpu
            name: k8s.resources.requests.cpu
            visibility: '$exists($value)'
          - source: spec.components.pilot.k8s.resources.requests.memory
            name: k8s.resources.requests.memory
            visibility: '$exists($value)'

        - widget: Panel
          name: Ingress Gateway
          visibility: '$exists(spec.components.ingressGateway.k8s.hpaSpec.minReplicas) or $exists(spec.components.ingressGateway.k8s.hpaSpec.maxReplicas) or $exists(spec.components.ingressGateway.k8s.strategy.rollingUpdate.maxSurge) or  $exists(spec.components.ingressGateway.k8s.strategy.rollingUpdate.maxUnavailable) or $exists(spec.components.ingressGateway.k8s.resources.limits.cpu) or $exists(spec.components.ingressGateway.k8s.resources.limits.memory) or $exists(spec.components.ingressGateway.k8s.resources.requests.cpu) or $exists(spec.components.ingressGateway.k8s.resources.requests.memory)'
          children:
          - source: spec.components.ingressGateway.k8s.hpaSpec.minReplicas
            name: k8s.hpaSpec.minReplicas
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.hpaSpec.maxReplicas
            name: k8s.hpaSpec.maxReplicas
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.strategy.rollingUpdate.maxSurge
            name: k8s.strategy.rollingUpdate.maxSurge
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.strategy.rollingUpdate.maxUnavailable
            name: k8s.strategy.rollingUpdate.maxUnavailable
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.resources.limits.cpu
            name: k8s.resources.limits.cpu
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.resources.limits.memory
            name: k8s.resources.limits.memory
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.resources.requests.cpu
            name: k8s.resources.requests.cpu
            visibility: '$exists($value)'
          - source: spec.components.ingressGateway.k8s.resources.requests.memory
            name: k8s.resources.requests.memory
            visibility: '$exists($value)'

        - widget: Panel
          name: CNI
          visibility: '$exists(spec.components.cni.k8s.resources.limits.cpu) or $exists(spec.components.cni.k8s.resources.limits.memory) or $exists(spec.components.cni.k8s.resources.requests.cpu) or  $exists(spec.components.cni.k8s.resources.requests.memory) or $exists(spec.components.cni.k8s.affinity)'
          children:
            - source: spec.components.cni.k8s.resources.limits.cpu
              name: k8s.resources.limits.cpu
              visibility: '$exists($value)'
            - source: spec.components.cni.k8s.resources.limits.memory
              name: k8s.resources.limits.memory
              visibility: '$exists($value)'
            - source: spec.components.cni.k8s.resources.requests.cpu
              name: k8s.resources.requests.cpu
              visibility: '$exists($value)'
            - source: spec.components.cni.k8s.resources.requests.memory
              name: k8s.resources.requests.memory
              visibility: '$exists($value)'
            - source: spec.components.cni.k8s.affinity
              name: k8s.affinity
              widget: CodeViewer
              description: "Kubernetes documentation for {{[Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)}}"
              language: "'yaml'"
              visibility: '$exists($value)'

        - widget: Panel
          name: Proxy
          visibility: '$exists(spec.components.proxy.k8s.resources.limits.cpu) or $exists(spec.components.proxy.k8s.resources.limits.memory) or $exists(spec.components.proxy.k8s.resources.requests.cpu) or  $exists(spec.components.proxy.k8s.resources.requests.memory)'
          children:
          - source: spec.components.proxy.k8s.resources.limits.cpu
            name: k8s.resources.limits.cpu
            visibility: '$exists($value)'
          - source: spec.components.proxy.k8s.resources.limits.memory
            name: k8s.resources.limits.memory
            visibility: '$exists($value)'
          - source: spec.components.proxy.k8s.resources.requests.cpu
            name: k8s.resources.requests.cpu
            visibility: '$exists($value)'
          - source: spec.components.proxy.k8s.resources.requests.memory
            name: k8s.resources.requests.memory
            visibility: '$exists($value)'

    - source: status.conditions
      widget: Table
      name: Reconciliation Conditions
      children:
        - source: type
          name: Type
        - source: status
          name: Status
          widget: Badge
          highlights:
            success:
              - 'True'
            error:
              - 'False'
        - source: reason
          name: Reason
        - source: message
          name: Message
        - source: '$readableTimestamp(lastTransitionTime)'
          name: Last transition
          sort: true
  form: |
    - path: spec
      simple: true
      name: General
      widget: FormGroup
      defaultExpanded: true
      children:
      - path: config.gatewayExternalTrafficPolicy
        name: config.gatewayExternalTrafficPolicy
        simple: true
        description: description.externalTrafficPolicy
        value:
          type: string
      - path: config.numTrustedProxies
        simple: true
        name: config.numTrustedProxies
        value:
          type: number
      - path: compatibilityMode
        simple: true
        name: compatibilityMode
        value:
          type: bool
      - path: config.telemetry.metrics.prometheusMerge
        simple: true
        name: config.prometheusMerge
        value:
          type: bool
    - path: spec.config.authorizers
      name: config.authorizers
      widget: GenericList
      children:
        - path: '].name'
          name: config.authorizers.name
        - path: '].service'
          name: config.authorizers.service
        - path: '].port'
          name: config.authorizers.port
        - path: '].headers'
          name: config.authorizers.headers
          widget: FormGroup
          children:
          - path: 'inCheck.add'
            name: config.authorizers.headers.inCheck.add
            widget: KeyValuePair
          - path: 'inCheck.include'
            name: config.authorizers.headers.inCheck.include
            widget: SimpleList
            children:
                - path: ']'
          - path: 'toUpstream.onAllow'
            name: config.authorizers.headers.toUpstream.onAllow
            widget: SimpleList
            children:
                - path: ']'
          - path: 'toDownstream.onAllow'
            name: config.authorizers.headers.toDownstream.onAllow
            widget: SimpleList
            children:
                - path: ']'
          - path: 'toDownstream.onDeny'
            name: config.authorizers.headers.toDownstream.onDeny
            widget: SimpleList
            children:
                - path: ']'

    - path: spec.components
      name: Components
      widget: FormGroup
      defaultExpanded: true
      children:
      - path: 'pilot'
        required: false
        name: Pilot
        widget: FormGroup
        defaultExpanded: false
        children:
        - path: 'k8s.hpaSpec'
          name: k8s.hpaSpec
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'minReplicas'
            name: k8s.hpaSpec.minReplicas
            description: description.hpaSpec.minReplicas
            value:
              type: number
          - path: 'maxReplicas'
            name: k8s.hpaSpec.maxReplicas
            description: description.hpaSpec.maxReplicas
            value:
              type: number
        - path: 'k8s.strategy.rollingUpdate'
          required: false
          name: k8s.strategy.rollingUpdate
          widget: FormGroup
          defaultExpanded: false
          type: object
          properties:
            maxSurge:
              type: string
            maxUnavailable:
              type: string
          children:
          - path: 'maxSurge'
            name: k8s.strategy.rollingUpdate.maxSurge
            description: description.rollingUpdate.maxSurge
            value:
              type: string
              pattern: ^\d+%?$
          - path: 'maxUnavailable'
            name: k8s.strategy.rollingUpdate.maxUnavailable
            description: description.rollingUpdate.maxUnvailable
            value:
              type: string
              pattern: ^\d+%?$
        - path: 'k8s.resources.limits'
          name: Resource Limits
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.limits.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.limits.memory
        - path: 'k8s.resources.requests'
          name: Resource Requests
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.requests.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.requests.memory
      - path: 'ingressGateway'
        required: false
        name: Ingress Gateway
        widget: FormGroup
        defaultExpanded: false
        children:
        - path: 'k8s.hpaSpec'
          name: k8s.hpaSpec
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'minReplicas'
            name: k8s.hpaSpec.minReplicas
            description: description.hpaSpec.minReplicas
            value:
              type: number
          - path: 'maxReplicas'
            name: k8s.hpaSpec.maxReplicas
            description: description.hpaSpec.maxReplicas
            value:
              type: number
        - path: 'k8s.strategy.rollingUpdate'
          required: false
          name: k8s.strategy.rollingUpdate
          widget: FormGroup
          defaultExpanded: false
          type: object
          properties:
            maxSurge:
              type: string
            maxUnavailable:
              type: string
          children:
          - path: 'maxSurge'
            name: k8s.strategy.rollingUpdate.maxSurge
            description: description.rollingUpdate.maxSurge
            value:
              type: string
              pattern: ^\d+%?$
          - path: 'maxUnavailable'
            name: k8s.strategy.rollingUpdate.maxUnavailable
            description: description.rollingUpdate.maxUnvailable
            value:
              type: string
              pattern: ^\d+%?$
        - path: 'k8s.resources.limits'
          name: Resource Limits
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.limits.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.limits.memory
        - path: 'k8s.resources.requests'
          name: Resource Requests
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.requests.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.requests.memory
      - path: 'cni'
        required: false
        name: CNI
        widget: FormGroup
        defaultExpanded: false
        children:
        - path: 'k8s.affinity'
          widget: CodeEditor
          description: k8s.affinity
          language: "'yaml'"
        - path: 'k8s.resources.limits'
          name: Resource Limits
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.limits.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.limits.memory
        - path: 'k8s.resources.requests'
          name: Resource Requests
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.requests.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.requests.memory
      - path: 'proxy'
        required: false
        name: Proxy
        widget: FormGroup
        defaultExpanded: false
        children:
        - path: 'k8s.resources.limits'
          name: Resource Limits
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.limits.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.limits.memory
        - path: 'k8s.resources.requests'
          name: Resource Requests
          widget: FormGroup
          defaultExpanded: false
          children:
          - path: 'cpu'
            name: k8s.resources.cpu
            description: description.requests.cpu
          - path: 'memory'
            name: k8s.resources.memory
            description: description.requests.memory
  general: |-
    resource:
      kind: Istio
      group: operator.kyma-project.io
      version: v1alpha2
    urlPath: istios
    category: Kyma
    name: Istio
    scope: namespace
    features:
      actions:
        disableCreate: true
        disableDelete: true
    description: >-
      {{[Istio custom resource ](https://kyma-project.io/#/istio/user/04-00-istio-custom-resource)}}
      configures the Istio module.
  list: |
    - name: Ready
      source: status.state
      widget: Badge
      description: status.description
      highlights:
        positive:
          - 'Ready'
        negative:
          - 'Error'
        critical:
          - 'Warning'
  translations: |
    en:
      compatibilityMode: Compatibility Mode
      config.numTrustedProxies: Number of trusted proxies

      config.authorizers: Authorizers
      config.authorizers.name: Name
      config.authorizers.service: Service
      config.authorizers.port: Port
      config.authorizers.headers: Headers
      config.authorizers.headers.inCheck.include: Forward To Authorization Request
      config.authorizers.headers.inCheck.add: Add To Authorization Request
      config.authorizers.headers.toUpstream.onAllow: Forward To Upstream
      config.authorizers.headers.toDownstream.onAllow: Forward To Downstream On Allow
      config.authorizers.headers.toDownstream.onDeny: Forward To Downstream On Deny
      config.gatewayExternalTrafficPolicy: Gateway external traffic policy
      config.prometheusMerge: Enable PrometheusMerge

      k8s.hpaSpec: Horizontal Pod Autoscaler
      k8s.hpaSpec.minReplicas: Minimum number of replicas
      k8s.hpaSpec.maxReplicas: Maximum number of replicas
      k8s.strategy.rollingUpdate: Rolling update strategy
      k8s.strategy.rollingUpdate.maxSurge: Maximum surge
      k8s.strategy.rollingUpdate.maxUnavailable: Maximum unavailable
      k8s.resources.cpu: CPU
      k8s.resources.memory: Memory
      k8s.resources.limits.cpu: CPU limits
      k8s.resources.limits.memory: Memory limits
      k8s.resources.requests.cpu: CPU requests
      k8s.resources.requests.memory: Memory requests
      k8s.affinity: Affinity (YAML)
      description.hpaSpec.minReplicas: Minimum number of replicas for this deployment
      description.hpaSpec.maxReplicas: Maximum number of replicas for this deployment
      description.rollingUpdate.maxSurge: Maximum number of Pods, or the percentage of Pods that can be created on top during an update
      description.rollingUpdate.maxUnvailable: Maximum number of Pods, or the percentage of Pods that can be unavailable during an update
      description.limits.cpu: Total CPU limits of all Pods that are in a non-terminal state must not exceed this value
      description.limits.memory: Total memory limits of all Pods that are in a non-terminal state must not exceed this value
      description.requests.cpu: Total CPU requests of all Pods that are in a non-terminal state must not exceed this value
      description.requests.memory: Total memory requests of all Pods that are in a non-terminal state must not exceed this value
      description.externalTrafficPolicy: Specifies externalTrafficPolicy for the Istio Ingress Gateway Service
      description.compatibilityMode: Sets Istio compatibility version the last minor version.
```
