### ISSUE TITLE
Jobs and corncobs created from Busola have Istio sidecards

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#921]
**Description**

Jobs and corncobs created from Busola have Istio sidecards
**Expected result**

Jobs and corncobs created from Busola should have the  option to remove the Istio sidecards

**Actual result**

Jobs and corncobs created from Busola have Istio sidecards and there is no way to disable them

**Steps to reproduce**

Create a job - and see the sidecards in the generated pod

**Troubleshooting**

We should consider adding by default the annotation when ISTIO is present in the system
```
spec:
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false" 
```
